# Generated by Django 5.0.1 on 2024-01-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schedule_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
