# Generated by Django 5.0.1 on 2024-01-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_list', '0002_guestspace'),
        ('user', '0002_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestspace',
            name='Schedule_id',
        ),
        migrations.RemoveField(
            model_name='guestspace',
            name='user_id',
        ),
        migrations.AddField(
            model_name='guestspace',
            name='schedule',
            field=models.ForeignKey(db_column='schedule_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule_list.schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestspace',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
