# Generated by Django 5.0.1 on 2024-01-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_list', '0003_remove_guestspace_schedule_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='host_name',
        ),
        migrations.AddField(
            model_name='schedule',
            name='guest_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='host_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
