# Generated by Django 5.0.1 on 2024-01-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_list', '0004_remove_schedule_guest_name_remove_schedule_host_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='guest_id',
        ),
    ]
