# Generated by Django 5.0.1 on 2024-01-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_list', '0006_schedulelike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulelike',
            old_name='schedule_id',
            new_name='Schedule',
        ),
        migrations.RenameField(
            model_name='schedulelike',
            old_name='user_id',
            new_name='user',
        ),
    ]
