# Generated by Django 5.0.1 on 2024-01-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_list', '0007_rename_schedule_id_schedulelike_schedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulelike',
            old_name='Schedule',
            new_name='schedule',
        ),
    ]
